### ISSUE TITLE
Docs for the SDK 

### ISSUE THREAD

**Issue by joelr-cm** [StonlyHQ/stonly-android-sdk#1]
Hey Stonly Team,

Could you share the docs on how to use the SDK ?

**Comment by yadaniyil** [comment]
The previous SDK that is
```
dependencies {
  implementation "stonly-library:stonly:1.0.5"
}
```

**Comment by Bkh84** [comment]
Hello.
We now have a complete new SDK for mobile, implementing everything you were able to do previously on the previous SDK. We no longer support the previous SDK
You need to go threw our support to activate your account and enjoy the new features. It also contains new features like a way to directly show triggers on your app.
[support@stonly.com](mailto:support@stonly.com)
